<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="appledeMacBook-Pro.local" ignored="1" name="其他功能" tests="2" failures="1" timestamp="23 Nov 2020 09:13:41 GMT" time="3.056" errors="0">
  <testcase name="testCase2" time="3.017" classname="com.panyu.mytestng.OtherTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.panyu.mytestng.OtherTest.testCase2() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.panyu.mytestng.OtherTest.testCase2() didn't finish within the time-out 3000
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:713)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.0" classname="com.panyu.mytestng.OtherTest"/>
  <testcase name="testCase1" time="0.0" classname="com.panyu.mytestng.OtherTest">
    <ignored/>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- 其他功能 -->
